on: [push] 
name: AzureARMDeploy

jobs:
  
 deploy:
   runs-on: ubuntu-latest
   steps:

   - name: Login to Azure           
     uses: azure/login@v1
     with:
        creds: ${{ secrets.AZURE_CREDENTIAL}}
    
   - name: checkout source code
     uses: actions/checkout@v1
      
   - name: ARM deployement
     uses: azure/CLI@v1
     with:
          inlinescript: |
           az deployment group create  
           --resource-group POC_DevOps_RG 
           --name storageAccountDeployement \
           --template-file storagegithubsri.json \
           --parameters storagename=stor11115




