cd:[push]

name:ArmDeploy

jobs:
  
 deploy:
   runs-on: ubuntu-latest
   steps:

   - name: Login to Azure           
     uses: azure/login@v1
     with:
        creds: ${{ secrets.SRI_SECRET_CRED }}
    
        - name: Run a one-line script
          uses:actions/checkout@v1
      
        - name: armdeployement
          uses:azure/CLI@v1
          with:
            inlinescript: |

             az deployment  group create\ 
             --name storageAccountDeployement\
             --resource-group storgithubrg\
             --template-file armgithub/storageaccount1.json\
             --parameters stoarageAccountType-Standard_LRS



